# docker build . -t <your username>/node-web-app
# docker run -p 49160:8080 -d <your username>/node-web-app

FROM node:latest

WORKDIR /app

COPY package*.json ./
COPY producer.js ./

RUN npm install
EXPOSE 3000

ENTRYPOINT ["npm", "run", "producer"]